## method :1

In [ ]:
import pandas as pd
import numpy as np
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import sent_tokenize

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
with open("t19_data.txt",'r') as f:
    lines = f.read()

In [ ]:
tk = sent_tokenize(lines)

In [ ]:
tk

['Can you please pass me the salt?',
 'I will meet you at the park in 30 minutes.',
 'I need to finish this work before the deadline.',
 'What time does the movie start tonight?',
 'Please do not forget to lock the door when you leave.']

In [ ]:
x_new = tfidf.fit_transform(tk)

In [ ]:
# x_new.toarray()

In [ ]:
tfdf = pd.DataFrame(data=x_new.toarray(), columns=tfidf.get_feature_names_out())
tfdf

,30,at,before,can,deadline,do,does,door,finish,forget,...,the,this,time,to,tonight,what,when,will,work,you
0,0.000000,0.000000,0.000000,0.433291,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.206465,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.290180
1,0.360948,0.360948,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.171994,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.360948,0.000000,0.241731
2,0.000000,0.000000,0.381303,0.000000,0.381303,0.000000,0.000000,0.000000,0.381303,0.000000,...,0.181693,0.381303,0.000000,0.307633,0.000000,0.000000,0.000000,0.000000,0.381303,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.400736,0.000000,0.000000,0.000000,...,0.190953,0.000000,0.400736,0.000000,0.400736,0.400736,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.333753,0.000000,0.333753,0.000000,0.333753,...,0.159035,0.000000,0.000000,0.269269,0.000000,0.000000,0.333753,0.000000,0.000000,0.223518

##  Method :2

In [ ]:
with open("t19_data.txt",'r') as f:
    x_new = tfidf.fit_transform(f.readlines())

In [ ]:
tfdf = pd.DataFrame(data=x_new.toarray(), columns=tfidf.get_feature_names_out())
tfdf

,30,at,before,can,deadline,do,does,door,finish,forget,...,the,this,time,to,tonight,what,when,will,work,you
0,0.000000,0.000000,0.000000,0.433291,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.206465,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.290180
1,0.360948,0.360948,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.171994,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.360948,0.000000,0.241731
2,0.000000,0.000000,0.381303,0.000000,0.381303,0.000000,0.000000,0.000000,0.381303,0.000000,...,0.181693,0.381303,0.000000,0.307633,0.000000,0.000000,0.000000,0.000000,0.381303,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.400736,0.000000,0.000000,0.000000,...,0.190953,0.000000,0.400736,0.000000,0.400736,0.400736,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.333753,0.000000,0.333753,0.000000,0.333753,...,0.159035,0.000000,0.000000,0.269269,0.000000,0.000000,0.333753,0.000000,0.000000,0.223518